service: bf-web

frameworkVersion: '>=1.2.0 <2.0.0'

provider:
  name: aws

functions:
  terp-email:
    handler: terp/index.email
    events:
      - http:
          path: api/terp/email
          method: get

package:
  exclude:
    - node_modules/serverless/**
